package com.scannerpro.lectorqr.presentation.navigation

sealed class Screen(val route: String) {
    object Scanner : Screen("scanner")
    object QrTypeSelection : Screen("qr_type_selection")
    object CreateQr : Screen("create_qr")
    object CreateContact : Screen("create_contact")
    object CreateUrl : Screen("create_url")
    object CreateText : Screen("create_text")
    object CreateEmail : Screen("create_email")
    object CreateSms : Screen("create_sms")
    object CreatePhone : Screen("create_phone")
    object CreateWifi : Screen("create_wifi")
    object CreateLocation : Screen("create_location")
    object CreateCalendar : Screen("create_calendar")
    object CreateWhatsApp : Screen("create_whatsapp")
    object CreateInstagram : Screen("create_instagram")
    object CreateFacebook : Screen("create_facebook")
    object CreateYouTube : Screen("create_youtube")
    object CreateTwitter : Screen("create_twitter")
    object CreateLinkedIn : Screen("create_linkedin")
    object CreateTikTok : Screen("create_tiktok")
    object CreateEan8 : Screen("create_ean8")
    object CreateEan13 : Screen("create_ean13")
    object CreateUpce : Screen("create_upce")
    object CreateUpca : Screen("create_upca")
    object CreateCode39 : Screen("create_code39")
    object CreateCode93 : Screen("create_code93")
    object CreateCode128 : Screen("create_code128")
    object CreateItf : Screen("create_itf")
    object CreatePdf417 : Screen("create_pdf417")
    object CreateCodabar : Screen("create_codabar")
    object CreateDataMatrix : Screen("create_datamatrix")
    object CreateAztec : Screen("create_aztec")
    object History : Screen("history")
    object Favorites : Screen("favorites")
    object Settings : Screen("settings")
    object Premium : Screen("premium")
    object ScanResult : Screen("scan_result/{scanId}") {
        fun createRoute(scanId: Long) = "scan_result/$scanId"
    }
}
